// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUCpx50qoaOH-KRjBrYyo-g5XKUFjLiY',
    appId: '1:201683354793:web:ad63868b8eb7d782cf55b8',
    messagingSenderId: '201683354793',
    projectId: 'belkis-market',
    authDomain: 'belkis-market.firebaseapp.com',
    databaseURL: 'https://belkis-market-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-market.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fzAntXZ_vn3520m5sqtrd76IRb-q6HM',
    appId: '1:201683354793:android:1f08eed2cc714cd2cf55b8',
    messagingSenderId: '201683354793',
    projectId: 'belkis-market',
    databaseURL: 'https://belkis-market-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxc3zXjLKmLzpDO9c5UL-xuIFZ0hBzV1Y',
    appId: '1:201683354793:ios:eb4f1070af6ef7ffcf55b8',
    messagingSenderId: '201683354793',
    projectId: 'belkis-market',
    databaseURL: 'https://belkis-market-default-rtdb.firebaseio.com',
    storageBucket: 'belkis-market.appspot.com',
    iosBundleId: 'com.example.admin',
  );
}
